# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
openapi: 3.0.3
info:
  title: "User Service API"
  description: "User Service API"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /user:
    get:
      operationId: "src.routes.user.read_all"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully read user list"
  /user/{email}:
    get:
      operationId: "src.routes.user.get_one"  
      summary: "Get user detail based on email ID"
      parameters:
        - $ref: '#components/parameters/email'
      responses:
        "200":
          description: "Successfully read user"

components:
  parameters:
    email:
      name: "email"
      description: "Email ID"
      in: path
      required: true
      schema:
        type: string
        format: email