# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
openapi: 3.0.3
info:
  title: "User Service API"
  description: "User Service API"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /user:
    get:
      operationId: "src.routes.user.read_all"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully read user list"
    